#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: 0e943c4d6d45ebd6deb75cb97a044167d13ccf8bef881d45a1057dc39e7f0b4c
          steroidsAppId:
            type: integer
            example: 1234
            default: 86944
  
schemas:
  - Space_collection: '{"$schema":"http://json-schema.org/schema","title":"Space collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Space representation","properties":{"Address":{"type":"string"},"Location":{"type":"object"},"Name":{"type":"string"},"Seat1":{"type":"integer"},"Seat2":{"type":"integer"},"Seat3":{"type":"integer"},"Seat4":{"type":"integer"},"createdAt":{"type":"string"},"objectId":{"type":"string"},"updatedAt":{"type":"string"}},"required":[]}}}}'
  - Space_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Space representation","properties":{"Address":{"type":"string"},"Location":{"type":"object"},"Name":{"type":"string"},"Seat1":{"type":"integer"},"Seat2":{"type":"integer"},"Seat3":{"type":"integer"},"Seat4":{"type":"integer"},"createdAt":{"type":"string"},"objectId":{"type":"string"},"updatedAt":{"type":"string"}},"required":[]}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:

  - parse_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "results"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - parse_member:
      usage: This resourceType should be used for any parse item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Space:
  description: |
    {
      "resourceName": "Space",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member


